[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MiniZinc = "a7f392d2-6c35-496e-b8cc-0974fbfcbf91"
ORTools_jll = "717719f8-c30c-5086-8f3c-70cd6a1e3a46"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
